# Project tasks are loaded only after build:run-task is invoked.
task=build-headless
executable=./scripts/build.sh
cwd=.

task=test-headless
executable=./scripts/test.sh
cwd=.

task=build-sdl
executable=./scripts/build-sdl.sh
cwd=.
