/* Generated by Haxeon. Do not edit. */
#ifndef PRAGTICAL_HX_FFI_H
#define PRAGTICAL_HX_FFI_H

#include <hl.h>

#define PRAGTICAL_HX_FFI_H_SIGNATURE 0x12B2490Fu

HL_PRIM int pragtical_hx_abi_version(void);
HL_PRIM vbyte * pragtical_hx_clipboard_get(void);
HL_PRIM bool pragtical_hx_clipboard_set(vbyte * arg0);
HL_PRIM bool pragtical_hx_draw_rect(int arg0, int arg1, int arg2, int arg3, int arg4, int arg5);
HL_PRIM bool pragtical_hx_draw_text(int arg0, int arg1, int arg2, int arg3, vbyte * arg4, int arg5);
HL_PRIM int pragtical_hx_event_a(void);
HL_PRIM int pragtical_hx_event_b(void);
HL_PRIM int pragtical_hx_event_c(void);
HL_PRIM int pragtical_hx_event_d(void);
HL_PRIM int pragtical_hx_event_kind(void);
HL_PRIM bool pragtical_hx_event_poll(void);
HL_PRIM bool pragtical_hx_event_push_test(int arg0, int arg1, int arg2, int arg3);
HL_PRIM vbyte * pragtical_hx_event_text(void);
HL_PRIM int pragtical_hx_event_window(void);
HL_PRIM int pragtical_hx_font_create(int arg0, vbyte * arg1, int arg2);
HL_PRIM bool pragtical_hx_font_destroy(int arg0);
HL_PRIM int pragtical_hx_font_height(int arg0);
HL_PRIM int pragtical_hx_font_text_width(int arg0, vbyte * arg1);
HL_PRIM bool pragtical_hx_frame_begin(int arg0);
HL_PRIM int pragtical_hx_frame_count(int arg0);
HL_PRIM bool pragtical_hx_frame_present(int arg0);
HL_PRIM void pragtical_hx_host_install(vclosure * arg0, vclosure * arg1, vclosure * arg2);
HL_PRIM bool pragtical_hx_init(bool arg0);
HL_PRIM vbyte * pragtical_hx_last_error(void);
HL_PRIM vbyte * pragtical_hx_plugin_api_call(int arg0, vbyte * arg1, vbyte * arg2, vbyte * arg3, vbyte * arg4);
HL_PRIM void pragtical_hx_plugin_api_install(vclosure * arg0);
HL_PRIM bool pragtical_hx_process_add_argument(int arg0, vbyte * arg1);
HL_PRIM bool pragtical_hx_process_cancel(int arg0);
HL_PRIM bool pragtical_hx_process_close_stdin(int arg0);
HL_PRIM int pragtical_hx_process_create(vbyte * arg0, vbyte * arg1);
HL_PRIM bool pragtical_hx_process_destroy(int arg0);
HL_PRIM int pragtical_hx_process_exit_status(int arg0);
HL_PRIM bool pragtical_hx_process_set_environment(int arg0, vbyte * arg1, vbyte * arg2);
HL_PRIM bool pragtical_hx_process_start(int arg0);
HL_PRIM int pragtical_hx_process_state(int arg0);
HL_PRIM vbyte * pragtical_hx_process_stderr(int arg0);
HL_PRIM vbyte * pragtical_hx_process_stdout(int arg0);
HL_PRIM int pragtical_hx_process_write(int arg0, vbyte * arg1);
HL_PRIM bool pragtical_hx_set_clip_rect(int arg0, int arg1, int arg2, int arg3, int arg4);
HL_PRIM void pragtical_hx_shutdown(void);
HL_PRIM int pragtical_hx_window_create(vbyte * arg0, int arg1, int arg2);
HL_PRIM bool pragtical_hx_window_destroy(int arg0);
HL_PRIM int pragtical_hx_window_display_scale_milli(int arg0);
HL_PRIM int pragtical_hx_window_height(int arg0);
HL_PRIM bool pragtical_hx_window_valid(int arg0);
HL_PRIM int pragtical_hx_window_width(int arg0);

DEFINE_PRIM(_I32, abi_version, _NO_ARG);
DEFINE_PRIM(_BYTES, clipboard_get, _NO_ARG);
DEFINE_PRIM(_BOOL, clipboard_set, _BYTES);
DEFINE_PRIM(_BOOL, draw_rect, _I32 _I32 _I32 _I32 _I32 _I32);
DEFINE_PRIM(_BOOL, draw_text, _I32 _I32 _I32 _I32 _BYTES _I32);
DEFINE_PRIM(_I32, event_a, _NO_ARG);
DEFINE_PRIM(_I32, event_b, _NO_ARG);
DEFINE_PRIM(_I32, event_c, _NO_ARG);
DEFINE_PRIM(_I32, event_d, _NO_ARG);
DEFINE_PRIM(_I32, event_kind, _NO_ARG);
DEFINE_PRIM(_BOOL, event_poll, _NO_ARG);
DEFINE_PRIM(_BOOL, event_push_test, _I32 _I32 _I32 _I32);
DEFINE_PRIM(_BYTES, event_text, _NO_ARG);
DEFINE_PRIM(_I32, event_window, _NO_ARG);
DEFINE_PRIM(_I32, font_create, _I32 _BYTES _I32);
DEFINE_PRIM(_BOOL, font_destroy, _I32);
DEFINE_PRIM(_I32, font_height, _I32);
DEFINE_PRIM(_I32, font_text_width, _I32 _BYTES);
DEFINE_PRIM(_BOOL, frame_begin, _I32);
DEFINE_PRIM(_I32, frame_count, _I32);
DEFINE_PRIM(_BOOL, frame_present, _I32);
DEFINE_PRIM(_VOID, host_install, _FUN(_VOID, _NO_ARG) _FUN(_I32, _NO_ARG) _FUN(_VOID, _NO_ARG));
DEFINE_PRIM(_BOOL, init, _BOOL);
DEFINE_PRIM(_BYTES, last_error, _NO_ARG);
DEFINE_PRIM(_BYTES, plugin_api_call, _I32 _BYTES _BYTES _BYTES _BYTES);
DEFINE_PRIM(_VOID, plugin_api_install, _FUN(_BYTES, _I32 _BYTES _BYTES _BYTES _BYTES));
DEFINE_PRIM(_BOOL, process_add_argument, _I32 _BYTES);
DEFINE_PRIM(_BOOL, process_cancel, _I32);
DEFINE_PRIM(_BOOL, process_close_stdin, _I32);
DEFINE_PRIM(_I32, process_create, _BYTES _BYTES);
DEFINE_PRIM(_BOOL, process_destroy, _I32);
DEFINE_PRIM(_I32, process_exit_status, _I32);
DEFINE_PRIM(_BOOL, process_set_environment, _I32 _BYTES _BYTES);
DEFINE_PRIM(_BOOL, process_start, _I32);
DEFINE_PRIM(_I32, process_state, _I32);
DEFINE_PRIM(_BYTES, process_stderr, _I32);
DEFINE_PRIM(_BYTES, process_stdout, _I32);
DEFINE_PRIM(_I32, process_write, _I32 _BYTES);
DEFINE_PRIM(_BOOL, set_clip_rect, _I32 _I32 _I32 _I32 _I32);
DEFINE_PRIM(_VOID, shutdown, _NO_ARG);
DEFINE_PRIM(_I32, window_create, _BYTES _I32 _I32);
DEFINE_PRIM(_BOOL, window_destroy, _I32);
DEFINE_PRIM(_I32, window_display_scale_milli, _I32);
DEFINE_PRIM(_I32, window_height, _I32);
DEFINE_PRIM(_BOOL, window_valid, _I32);
DEFINE_PRIM(_I32, window_width, _I32);

#endif /* PRAGTICAL_HX_FFI_H */
