#!/usr/bin/env python3
import argparse
import json
from pathlib import Path
import sys


ROOT = Path(__file__).resolve().parent.parent
SCHEMA = ROOT / "platform" / "abi.json"
C_OUTPUT = ROOT / "include" / "pragtical_hx" / "platform_abi.h"
HAXE_OUTPUT = ROOT / "src" / "platform" / "PlatformAbi.hx"
EVENT_OUTPUT = ROOT / "src" / "platform" / "PlatformEvent.hx"
DECODER_OUTPUT = ROOT / "src" / "platform" / "PlatformEventDecoder.hx"


def c_enum(name, prefix, values):
    members = list(values.items())
    lines = [f"typedef enum {name} {{"]
    for index, (key, value) in enumerate(members):
        comma = "," if index + 1 < len(members) else ""
        lines.append(f"  {prefix}{key} = {value}{comma}")
    lines.append(f"}} {name};")
    return "\n".join(lines)


def render_c(schema):
    modifiers = "\n".join(
        f"#define PHX_MOD_{key} {value}" for key, value in schema["modifiers"].items()
    )
    mouse = "\n".join(
        f"#define PHX_MOUSE_{key} {value}" for key, value in schema["mouse_buttons"].items()
    )
    return f"""/* Generated by scripts/generate-platform-abi.py from platform/abi.json. */
#ifndef PRAGTICAL_HX_PLATFORM_ABI_H
#define PRAGTICAL_HX_PLATFORM_ABI_H

#define PHX_PLATFORM_ABI_VERSION {schema['version']}

{c_enum('phx_event_kind', 'PHX_EVENT_', {key: event['value'] for key, event in schema['events'].items()})}

{c_enum('phx_key', 'PHX_KEY_', schema['keys'])}

{modifiers}

{mouse}

#endif
"""


def render_haxe(schema):
    constants = [("ABI_VERSION", schema["version"])]
    for section, prefix in (("events", "EVENT_"), ("keys", "KEY_"),
                            ("modifiers", "MOD_"), ("mouse_buttons", "MOUSE_")):
        constants.extend((prefix + key, value["value"] if section == "events" else value)
                         for key, value in schema[section].items())
    fields = "\n".join(
        f"\tpublic static inline final {name} = {value};" for name, value in constants
    )
    return f"""// Generated by scripts/generate-platform-abi.py from platform/abi.json.
package platform;

class PlatformAbi {{
{fields}
}}
"""


def field_name(field):
    return field[2] if len(field) == 3 else field[0]


def render_events(schema):
    constructors = []
    for event in schema["events"].values():
        if "constructor" not in event:
            continue
        fields = event["fields"]
        arguments = ", ".join(f"{field_name(field)}:{field[1]}" for field in fields)
        constructors.append(f"\t{event['constructor']}({arguments});" if arguments
                            else f"\t{event['constructor']};")
    return "// Generated by scripts/generate-platform-abi.py from platform/abi.json.\n" \
        "package platform;\n\nenum PlatformEvent {\n" + "\n".join(constructors) + "\n}\n"


def render_decoder(schema):
    access = {
        "window": "Native.event_window()", "a": "Native.event_a()",
        "b": "Native.event_b()", "c": "Native.event_c()",
        "d": "Native.event_d()", "text": "Native.event_text()"
    }
    cases = []
    for name, event in schema["events"].items():
        if "constructor" not in event:
            continue
        arguments = ", ".join(access[field[0]] for field in event["fields"])
        value = f"{event['constructor']}({arguments})" if arguments else event["constructor"]
        cases.append(f"\t\t\tcase PlatformAbi.EVENT_{name}: {value};")
    return "// Generated by scripts/generate-platform-abi.py from platform/abi.json.\n" \
        "package platform;\n\nclass PlatformEventDecoder {\n" \
        "\tpublic static function poll():Null<PlatformEvent> {\n" \
        "\t\tif (!Native.event_poll()) return null;\n\t\treturn switch Native.event_kind() {\n" + \
        "\n".join(cases) + "\n\t\t\tdefault: null;\n\t\t};\n\t}\n}\n"


def update(path, content, check):
    current = path.read_text() if path.exists() else None
    if current == content:
        return True
    if check:
        print(f"stale generated ABI file: {path.relative_to(ROOT)}", file=sys.stderr)
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content)
    return True


def validate(schema):
    allowed_sources = {"window": "Int", "a": "Int", "b": "Int", "c": "Int",
                       "d": "Int", "text": "String"}
    for section in ("events", "keys", "modifiers", "mouse_buttons"):
        values = [item["value"] for item in schema[section].values()] if section == "events" \
            else list(schema[section].values())
        if len(values) != len(set(values)):
            raise ValueError(f"duplicate numeric value in {section}")
    constructors = set()
    for name, event in schema["events"].items():
        constructor = event.get("constructor")
        if constructor is None:
            continue
        if constructor in constructors:
            raise ValueError(f"duplicate event constructor: {constructor}")
        constructors.add(constructor)
        field_names = set()
        for field in event.get("fields", []):
            source, field_type = field[:2]
            name = field_name(field)
            if allowed_sources.get(source) != field_type:
                raise ValueError(f"invalid source/type for {constructor}.{name}")
            if name in field_names:
                raise ValueError(f"duplicate field in {constructor}: {name}")
            field_names.add(name)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    schema = json.loads(SCHEMA.read_text())
    validate(schema)
    ok = update(C_OUTPUT, render_c(schema), args.check)
    ok = update(HAXE_OUTPUT, render_haxe(schema), args.check) and ok
    ok = update(EVENT_OUTPUT, render_events(schema), args.check) and ok
    ok = update(DECODER_OUTPUT, render_decoder(schema), args.check) and ok
    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
