package platform;

@:hlNative("pragtical_hx")
extern class Native {
	static function abi_version():Int;
	static function init(headless:Bool):Bool;
	static function shutdown():Void;
	static function last_error():String;
	static function window_create(title:String, width:Int, height:Int):Int;
	static function window_destroy(window:Int):Bool;
	static function window_valid(window:Int):Bool;
	static function window_width(window:Int):Int;
	static function window_height(window:Int):Int;
	static function window_display_scale_milli(window:Int):Int;
	static function text_input_area(window:Int, x:Int, y:Int, width:Int, height:Int, cursor:Int):Bool;
	static function event_poll():Bool;
	static function event_kind():Int;
	static function event_window():Int;
	static function event_a():Int;
	static function event_b():Int;
	static function event_c():Int;
	static function event_d():Int;
	static function event_text():String;
	static function event_push_test(kind:Int, window:Int, a:Int, b:Int):Bool;
	static function event_push_text_test(kind:Int, window:Int, a:Int, b:Int, text:String):Bool;
	static function clipboard_set(text:String):Bool;
	static function clipboard_get():String;
	static function frame_begin(window:Int):Bool;
	static function set_clip_rect(window:Int, x:Int, y:Int, width:Int, height:Int):Bool;
	static function draw_rect(window:Int, x:Int, y:Int, width:Int, height:Int, rgba:Int):Bool;
	static function font_create(window:Int, path:String, size:Int):Int;
	static function font_add_fallback(font:Int, path:String):Bool;
	static function font_fallback_count(font:Int):Int;
	static function font_destroy(font:Int):Bool;
	static function font_height(font:Int):Int;
	static function font_text_width(font:Int, text:String):Int;
	static function draw_text(window:Int, font:Int, x:Int, y:Int, text:String, rgba:Int):Bool;
	static function frame_present(window:Int):Bool;
	static function frame_count(window:Int):Int;
	static function process_create(executable:String, cwd:String):Int;
	static function process_add_argument(process:Int, argument:String):Bool;
	static function process_set_environment(process:Int, key:String, value:String):Bool;
	static function process_start(process:Int):Bool;
	static function process_write(process:Int, data:String):Int;
	static function process_close_stdin(process:Int):Bool;
	static function process_stdout(process:Int):String;
	static function process_stderr(process:Int):String;
	static function process_state(process:Int):Int;
	static function process_exit_status(process:Int):Int;
	static function process_cancel(process:Int):Bool;
	static function process_destroy(process:Int):Bool;
	static function plugin_api_install(dispatch:(Int, String, String, String, String)->String):Void;
	static function plugin_api_call(operation:Int, token:String, a:String, b:String, c:String):String;
	static function host_install(event:()->Void, iterate:()->Int, quit:()->Void):Void;
}
