// Generated by scripts/generate-platform-abi.py from platform/abi.json.
package platform;

class PlatformEventDecoder {
	public static function poll():Null<PlatformEvent> {
		if (!Native.event_poll()) return null;
		return switch Native.event_kind() {
			case PlatformAbi.EVENT_QUIT: Quit;
			case PlatformAbi.EVENT_WINDOW_RESIZED: WindowResize(Native.event_window(), Native.event_a(), Native.event_b());
			case PlatformAbi.EVENT_KEY_DOWN: KeyDown(Native.event_window(), Native.event_a(), Native.event_b());
			case PlatformAbi.EVENT_KEY_UP: KeyUp(Native.event_window(), Native.event_a(), Native.event_b());
			case PlatformAbi.EVENT_TEXT_INPUT: TextInput(Native.event_window(), Native.event_text());
			case PlatformAbi.EVENT_MOUSE_MOVED: MouseMove(Native.event_window(), Native.event_a(), Native.event_b(), Native.event_c(), Native.event_d());
			case PlatformAbi.EVENT_MOUSE_BUTTON_DOWN: MouseButtonDown(Native.event_window(), Native.event_a(), Native.event_b(), Native.event_c(), Native.event_d());
			case PlatformAbi.EVENT_MOUSE_BUTTON_UP: MouseButtonUp(Native.event_window(), Native.event_a(), Native.event_b(), Native.event_c(), Native.event_d());
			case PlatformAbi.EVENT_MOUSE_WHEEL: MouseWheel(Native.event_window(), Native.event_a(), Native.event_b());
			case PlatformAbi.EVENT_DISPLAY_SCALE_CHANGED: DisplayScaleChanged(Native.event_window(), Native.event_a());
			default: null;
		};
	}
}
